### ISSUE TITLE
Problem converting hg38 to hg19

### ISSUE THREAD

**Issue by nicokrez** [konstantint/pyliftover#11]
Hi,

when I check some coordinates converted by your tool to the out put from UCSC web (https://genome.ucsc.edu/cgi-bin/hgLiftOver) tool I get slight differences for some coordinates.

Same output:
hg38: chr1: 1753774 -> hg19 chr1:1685213 (UCSC and pyliftover)

different output:
hg38 chr1:182903 -> hg19 chr15:102518784 (pyliftover); hg19 chr15:102518786 (UCSC)

Kind regards

**Comment by konstantint** [comment]
Please remember that PyLiftover uses 0-based indexing and only does point conversions. To obtain an equivalent result via UCSC liftover, submit the data as BED (which is also 0-based), NOT in the chrX:a-b form (which is 1-based).

For example, the BED line

    chr1 146019500 146019501

converts to

    chr1	145415511	145415512

which matches the result of PyLiftover.

_Do note that since the very first version of PyLiftover was published 7 years ago, 10 issues have been reported, of which 8 (#2, #3, #4, #5, #6, #8, #10, #11) claim to observe differences with UCSC's output. All of them turned out to be false reports due to misunderstanding of the differences between 0-based and 1-based indexing. The chances are pretty high that PyLiftover reproduces UCSC's mapping technique correctly._
