### ISSUE TITLE
Missing Output for Some Positions

### ISSUE THREAD

**Issue by matty234** [konstantint/pyliftover#16]
Appreciate this is an old repository but just as a heads-up for future users: this library seems to miss positions. For example:

Some examples using hg19ToHg38.over.chain.gz (md5sum `35887f73fe5e2231656504d1f6430900`):
- chr6:915652 (UCSC liftover returns chr6:915402-915402), this library returns no matches
- chr17:296626 (UCSC liftover returns chr17:446835-446835), this library returns no matches
- chr12:153058 (UCSC liftover returns chr12_GL877875v1_alt:31786-31786), this library returns no matches

I'll create a PR when I've found the issue!

**Comment by matty234** [comment]
There also seem to be a few issues that give an output which is incorrect:

```
('chr2', 845936) (expected[i]: ('chr2', 850281), pyliftover[i]: ('chr2', 850329, 1, '+', 3910))
('chr2', 843218) (expected[i]: ('chr2', 847216), pyliftover[i]: ('chr2', 846736, 1, '+', 1043))
```

**Comment by konstantint** [comment]
Please note that this library uses 0-based coordinate indexing while the web-based tool uses 1-based indexing.

In particular, the examples you brought in your first comment should be converted as follows:

```
from pyliftover import LiftOver
lo = LiftOver('hg19', 'hg38')
[('chr6', 915151, '+', 15728552471)]
> [('chr6', 915401, '+', 15728552471)]  # Corresponds to chr6:915402 in 1-based indexing
lo.convert_coordinate('chr17', 296625)
> [('chr17', 446834, '+', 7373267797)]  # Corresponds to chr17:446835 in 1-based indexing
lo.convert_coordinate('chr12', 153057)
> [('chr12_GL877875v1_alt', 31785, '+', 127260)]  # Corresponds to chr12_GL877875v1_alt:31786
```

Quite a number of issues claiming to detect mismatches with UCSC Liftover have been reported ever since the algorithm was first implemented in 2013, yet not a single one of them turned out to be a valid bug requiring any change to the algorithm - it is  always related to confusion around 0-based and 1-based indexing.
