### ISSUE TITLE
Incorrect liftover from hg38 to scaffold in hg19

### ISSUE THREAD

**Issue by iljungr** [konstantint/pyliftover#2]
> lo = LiftOver('hg38', 'hg19')
> lo.convert_coordinate('chr1', 146685740)
[('chr1_gl000192_random', 269268, '-', 43465923)]

However if I submit chr1:146685740-146685740 to the liftover tool at https://genome.ucsc.edu/cgi-bin/hgLiftOver it reports the answer is chr1_gl000192_random:269270-269270

pyliftover is off by 2 nucleotides (269268 instead of 269270).

**Comment by iljungr** [comment]
Looks like this might be a general problem whenever the result strand is '-', even when the result is on a main chromosome. Here are more examples:
lo.convert(chr9, 61066335) -> [('chr9', 43891709, '-', 30766700)]; should be chr9:43891711
lo.convert(chr9, 41044501) -> [('chr9', 71002501, '-', 3827487)]; should be chr9:71002503
lo.convert(chr9, 41047538) -> [('chr9', 70999463, '-', 3827487)]; should be chr9:70999465
lo.convert(chr9, 61063756) -> [('chr9', 43894313, '-', 30766700)]; should be chr9:43894315
lo.convert(chr13, 86266842) -> [('chr16', 19800242, '-', 1543239)]; should be chr16:19800244
lo.convert(chr9, 41127236) -> [('chr9', 70919013, '-', 3827487)]; should be chr9:70919015

**Comment by konstantint** [comment]
Interesting. I'm traveling at the moment, but will take a look in two days or so.

**Comment by konstantint** [comment]
So I finally rechecked, and there is actually no problem here - the difference is simply due to the coordinate system you use to input coordinates to the liftover webtool:

  * When you write `chr1:10-10`, you are using the 1-based coordinate system for both the start and end positions and the interval is inclusive, i.e. this interval is the tenth base on chromosome 1.
  * When you use the BED format in the web tool (i.e. enter `chr1  9 10`), you are using the "python-style" interval, i.e. the start coordinate is 0-based while the end coordinate is 1-based. This particular example denotes the same tenth base on chromosome 1 (the first base would have index 0).
  * Finally, `PyLiftOver` always uses the "Python", 0-based indexing convention. I.e. `('chr1', 9) in this example.

Now, in your example, `lo.convert_coordinate('chr1', 146685740)` corresponds to either the 
`chr1:146685741-146685741` interval notation, or `chr1 146685740 146685741` in BED notation.

When submitted to the web tool the first one produces `chr1_gl000192_random:269269-269269`, which corresponds to `('chr1_gl000192_random', 269268)` in 0-based PyLiftover indexing.

Submitting the BED input produces the BED output `chr1_gl000192_random	269268	269269`, which again represents the same result as the one produced by PyLiftover.

I'll add all of the examples you found to the test suite now, but otherwise there's nothing to fix and everything works as expected.

**Comment by iljungr** [comment]
I should have read the documentation more carefully. Sorry to waste your time.

**Comment by konstantint** [comment]
That's OK. Testing stuff from time to time never hurts :)
