### ISSUE TITLE
Conversion results may differ from what is obtained with LiftOver

### ISSUE THREAD

**Issue by yvancluet** [konstantint/pyliftover#8]
I have found several conversion errors from hg19 to hg38, especially on coordinates that are very close to the beginning or end of the chromosomes.
For instance, Lift Genome Annotations gives this when you try to convert chr12:0-133,851,895 (corresponds to a chromosome 12 trisomy) --> chr12:45001-133265309. However, with PyLiftOver, results for both chr12-0 and chr12-133851895 are empty lists (conversion unsuccessful). This is not a '0-based or 1-based' problem, since I have the same results for chr12-1 and chr12-133851894 (and actually for much more 'inner' coordonates, such as chr12-10000).
Is there any way to correct this ?
Thank you in advance

**Comment by konstantint** [comment]
PyLiftOver can only do point conversions, hence your results may differ from a tool which attemps to convert whole regions.

In particular, note that the single point "chr12:0" does not have any match in the hg19-hg38 chain file, because of that you get an empty list there. You will get an empty list if you try using the original liftOver tool as well:
https://imgur.com/B6Pxbq1
What this means, in simple terms, is that the particular basepair was effectively "deleted" in the newer genome version (and possibly replaced with a completely different piece).

The possibility to convert full regions would be nice, but I never had a personal need nor found enough free time to implement it, nor received any contributed code regarding this functionality.
